# Specify the version of our docker compose syntax in case the new release version breaking our configurations
version: "3.9"

services:
  app:
    # Build the image in the current directory
    build:
      context: .
      args:
        - DEV=true
    # Map port 8000 in our local machine to port 8000 inside our docker container
    ports:
      - "8000:8000"
    # Map the app directory that we created for the project to the app directory inside the container
    # Automatically sync the project code without rebuilding the image
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      # Sets the environment variables
      # To set the initial database configurations for our new db service
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
volumes:
  dev-db-data:
