---
name: Checks

on: [push]

jobs:
  test-lint: # ID of the job
    name: Test and Lint # Human friendly name that you can see in your Github interface
    runs-on: ubuntu-20.04 # Runner for running our jobs. Options provided by Github Actions Repository
    steps: # Different steps that need to run for the job. Performed in order
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Allows you to use another pre-made action provided by Github Actions
        with: # Parameters
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout # Checks our code out inside the GitHub Actions job
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
